/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsTestRouteImport } from './routes/tools-test'
import { Route as MiddlewareTestRouteImport } from './routes/middleware-test'
import { Route as MarkdownCjkRouteImport } from './routes/markdown-cjk'
import { Route as DevtoolsToolsRouteImport } from './routes/devtools-tools'
import { Route as DevtoolsStructuredRouteImport } from './routes/devtools-structured'
import { Route as DevtoolsRouteBRouteImport } from './routes/devtools-route-b'
import { Route as DevtoolsRouteARouteImport } from './routes/devtools-route-a'
import { Route as DevtoolsGenerationHooksRouteImport } from './routes/devtools-generation-hooks'
import { Route as DevtoolsChatRouteImport } from './routes/devtools-chat'
import { Route as ChatClientDefaultBridgeRouteImport } from './routes/chat-client-default-bridge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/$provider/index'
import { Route as ApiVideoRouteImport } from './routes/api.video'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiTranscriptionRouteImport } from './routes/api.transcription'
import { Route as ApiToolsTestRouteImport } from './routes/api.tools-test'
import { Route as ApiToolCallLifecycleWireRouteImport } from './routes/api.tool-call-lifecycle-wire'
import { Route as ApiSummarizeRouteImport } from './routes/api.summarize'
import { Route as ApiOtelUsageRouteImport } from './routes/api.otel-usage'
import { Route as ApiOpenrouterWebToolsWireRouteImport } from './routes/api.openrouter-web-tools-wire'
import { Route as ApiOpenrouterCostRouteImport } from './routes/api.openrouter-cost'
import { Route as ApiOpenaiUsageDetailsRouteImport } from './routes/api.openai-usage-details'
import { Route as ApiOpenaiShellSkillsWireRouteImport } from './routes/api.openai-shell-skills-wire'
import { Route as ApiMultimodalToolResultWireRouteImport } from './routes/api.multimodal-tool-result-wire'
import { Route as ApiMiddlewareTestRouteImport } from './routes/api.middleware-test'
import { Route as ApiMcpTestRouteImport } from './routes/api.mcp-test'
import { Route as ApiMcpStatusTestRouteImport } from './routes/api.mcp-status-test'
import { Route as ApiMcpServerRouteImport } from './routes/api.mcp-server'
import { Route as ApiMcpManagedTestRouteImport } from './routes/api.mcp-managed-test'
import { Route as ApiMcpLifecycleTestRouteImport } from './routes/api.mcp-lifecycle-test'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAudioRouteImport } from './routes/api.audio'
import { Route as ApiArktypeToolWireRouteImport } from './routes/api.arktype-tool-wire'
import { Route as ApiAnthropicSkillsWireRouteImport } from './routes/api.anthropic-skills-wire'
import { Route as ApiAnthropicBugTestRouteImport } from './routes/api.anthropic-bug-test'
import { Route as ProviderFeatureRouteImport } from './routes/$provider/$feature'
import { Route as ApiVideoStreamRouteImport } from './routes/api.video.stream'
import { Route as ApiTtsStreamRouteImport } from './routes/api.tts.stream'
import { Route as ApiTranscriptionStreamRouteImport } from './routes/api.transcription.stream'
import { Route as ApiImageStreamRouteImport } from './routes/api.image.stream'
import { Route as ApiAudioStreamRouteImport } from './routes/api.audio.stream'

const ToolsTestRoute = ToolsTestRouteImport.update({
  id: '/tools-test',
  path: '/tools-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MiddlewareTestRoute = MiddlewareTestRouteImport.update({
  id: '/middleware-test',
  path: '/middleware-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownCjkRoute = MarkdownCjkRouteImport.update({
  id: '/markdown-cjk',
  path: '/markdown-cjk',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsToolsRoute = DevtoolsToolsRouteImport.update({
  id: '/devtools-tools',
  path: '/devtools-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsStructuredRoute = DevtoolsStructuredRouteImport.update({
  id: '/devtools-structured',
  path: '/devtools-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsRouteBRoute = DevtoolsRouteBRouteImport.update({
  id: '/devtools-route-b',
  path: '/devtools-route-b',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsRouteARoute = DevtoolsRouteARouteImport.update({
  id: '/devtools-route-a',
  path: '/devtools-route-a',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsGenerationHooksRoute = DevtoolsGenerationHooksRouteImport.update({
  id: '/devtools-generation-hooks',
  path: '/devtools-generation-hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsChatRoute = DevtoolsChatRouteImport.update({
  id: '/devtools-chat',
  path: '/devtools-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatClientDefaultBridgeRoute = ChatClientDefaultBridgeRouteImport.update({
  id: '/chat-client-default-bridge',
  path: '/chat-client-default-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/$provider/',
  path: '/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionRoute = ApiTranscriptionRouteImport.update({
  id: '/api/transcription',
  path: '/api/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsTestRoute = ApiToolsTestRouteImport.update({
  id: '/api/tools-test',
  path: '/api/tools-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolCallLifecycleWireRoute =
  ApiToolCallLifecycleWireRouteImport.update({
    id: '/api/tool-call-lifecycle-wire',
    path: '/api/tool-call-lifecycle-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtelUsageRoute = ApiOtelUsageRouteImport.update({
  id: '/api/otel-usage',
  path: '/api/otel-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterWebToolsWireRoute =
  ApiOpenrouterWebToolsWireRouteImport.update({
    id: '/api/openrouter-web-tools-wire',
    path: '/api/openrouter-web-tools-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenrouterCostRoute = ApiOpenrouterCostRouteImport.update({
  id: '/api/openrouter-cost',
  path: '/api/openrouter-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiUsageDetailsRoute = ApiOpenaiUsageDetailsRouteImport.update({
  id: '/api/openai-usage-details',
  path: '/api/openai-usage-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiShellSkillsWireRoute =
  ApiOpenaiShellSkillsWireRouteImport.update({
    id: '/api/openai-shell-skills-wire',
    path: '/api/openai-shell-skills-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMultimodalToolResultWireRoute =
  ApiMultimodalToolResultWireRouteImport.update({
    id: '/api/multimodal-tool-result-wire',
    path: '/api/multimodal-tool-result-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMiddlewareTestRoute = ApiMiddlewareTestRouteImport.update({
  id: '/api/middleware-test',
  path: '/api/middleware-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTestRoute = ApiMcpTestRouteImport.update({
  id: '/api/mcp-test',
  path: '/api/mcp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpStatusTestRoute = ApiMcpStatusTestRouteImport.update({
  id: '/api/mcp-status-test',
  path: '/api/mcp-status-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpServerRoute = ApiMcpServerRouteImport.update({
  id: '/api/mcp-server',
  path: '/api/mcp-server',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpManagedTestRoute = ApiMcpManagedTestRouteImport.update({
  id: '/api/mcp-managed-test',
  path: '/api/mcp-managed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpLifecycleTestRoute = ApiMcpLifecycleTestRouteImport.update({
  id: '/api/mcp-lifecycle-test',
  path: '/api/mcp-lifecycle-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArktypeToolWireRoute = ApiArktypeToolWireRouteImport.update({
  id: '/api/arktype-tool-wire',
  path: '/api/arktype-tool-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthropicSkillsWireRoute = ApiAnthropicSkillsWireRouteImport.update({
  id: '/api/anthropic-skills-wire',
  path: '/api/anthropic-skills-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthropicBugTestRoute = ApiAnthropicBugTestRouteImport.update({
  id: '/api/anthropic-bug-test',
  path: '/api/anthropic-bug-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderFeatureRoute = ProviderFeatureRouteImport.update({
  id: '/$provider/$feature',
  path: '/$provider/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStreamRoute = ApiVideoStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiVideoRoute,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiTtsRoute,
} as any)
const ApiTranscriptionStreamRoute = ApiTranscriptionStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiTranscriptionRoute,
} as any)
const ApiImageStreamRoute = ApiImageStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiImageRoute,
} as any)
const ApiAudioStreamRoute = ApiAudioStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiAudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-client-default-bridge': typeof ChatClientDefaultBridgeRoute
  '/devtools-chat': typeof DevtoolsChatRoute
  '/devtools-generation-hooks': typeof DevtoolsGenerationHooksRoute
  '/devtools-route-a': typeof DevtoolsRouteARoute
  '/devtools-route-b': typeof DevtoolsRouteBRoute
  '/devtools-structured': typeof DevtoolsStructuredRoute
  '/devtools-tools': typeof DevtoolsToolsRoute
  '/markdown-cjk': typeof MarkdownCjkRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/tools-test': typeof ToolsTestRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/anthropic-bug-test': typeof ApiAnthropicBugTestRoute
  '/api/anthropic-skills-wire': typeof ApiAnthropicSkillsWireRoute
  '/api/arktype-tool-wire': typeof ApiArktypeToolWireRoute
  '/api/audio': typeof ApiAudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/mcp-lifecycle-test': typeof ApiMcpLifecycleTestRoute
  '/api/mcp-managed-test': typeof ApiMcpManagedTestRoute
  '/api/mcp-server': typeof ApiMcpServerRoute
  '/api/mcp-status-test': typeof ApiMcpStatusTestRoute
  '/api/mcp-test': typeof ApiMcpTestRoute
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/multimodal-tool-result-wire': typeof ApiMultimodalToolResultWireRoute
  '/api/openai-shell-skills-wire': typeof ApiOpenaiShellSkillsWireRoute
  '/api/openai-usage-details': typeof ApiOpenaiUsageDetailsRoute
  '/api/openrouter-cost': typeof ApiOpenrouterCostRoute
  '/api/openrouter-web-tools-wire': typeof ApiOpenrouterWebToolsWireRoute
  '/api/otel-usage': typeof ApiOtelUsageRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tool-call-lifecycle-wire': typeof ApiToolCallLifecycleWireRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider/': typeof ProviderIndexRoute
  '/api/audio/stream': typeof ApiAudioStreamRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-client-default-bridge': typeof ChatClientDefaultBridgeRoute
  '/devtools-chat': typeof DevtoolsChatRoute
  '/devtools-generation-hooks': typeof DevtoolsGenerationHooksRoute
  '/devtools-route-a': typeof DevtoolsRouteARoute
  '/devtools-route-b': typeof DevtoolsRouteBRoute
  '/devtools-structured': typeof DevtoolsStructuredRoute
  '/devtools-tools': typeof DevtoolsToolsRoute
  '/markdown-cjk': typeof MarkdownCjkRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/tools-test': typeof ToolsTestRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/anthropic-bug-test': typeof ApiAnthropicBugTestRoute
  '/api/anthropic-skills-wire': typeof ApiAnthropicSkillsWireRoute
  '/api/arktype-tool-wire': typeof ApiArktypeToolWireRoute
  '/api/audio': typeof ApiAudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/mcp-lifecycle-test': typeof ApiMcpLifecycleTestRoute
  '/api/mcp-managed-test': typeof ApiMcpManagedTestRoute
  '/api/mcp-server': typeof ApiMcpServerRoute
  '/api/mcp-status-test': typeof ApiMcpStatusTestRoute
  '/api/mcp-test': typeof ApiMcpTestRoute
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/multimodal-tool-result-wire': typeof ApiMultimodalToolResultWireRoute
  '/api/openai-shell-skills-wire': typeof ApiOpenaiShellSkillsWireRoute
  '/api/openai-usage-details': typeof ApiOpenaiUsageDetailsRoute
  '/api/openrouter-cost': typeof ApiOpenrouterCostRoute
  '/api/openrouter-web-tools-wire': typeof ApiOpenrouterWebToolsWireRoute
  '/api/otel-usage': typeof ApiOtelUsageRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tool-call-lifecycle-wire': typeof ApiToolCallLifecycleWireRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider': typeof ProviderIndexRoute
  '/api/audio/stream': typeof ApiAudioStreamRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat-client-default-bridge': typeof ChatClientDefaultBridgeRoute
  '/devtools-chat': typeof DevtoolsChatRoute
  '/devtools-generation-hooks': typeof DevtoolsGenerationHooksRoute
  '/devtools-route-a': typeof DevtoolsRouteARoute
  '/devtools-route-b': typeof DevtoolsRouteBRoute
  '/devtools-structured': typeof DevtoolsStructuredRoute
  '/devtools-tools': typeof DevtoolsToolsRoute
  '/markdown-cjk': typeof MarkdownCjkRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/tools-test': typeof ToolsTestRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/anthropic-bug-test': typeof ApiAnthropicBugTestRoute
  '/api/anthropic-skills-wire': typeof ApiAnthropicSkillsWireRoute
  '/api/arktype-tool-wire': typeof ApiArktypeToolWireRoute
  '/api/audio': typeof ApiAudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/mcp-lifecycle-test': typeof ApiMcpLifecycleTestRoute
  '/api/mcp-managed-test': typeof ApiMcpManagedTestRoute
  '/api/mcp-server': typeof ApiMcpServerRoute
  '/api/mcp-status-test': typeof ApiMcpStatusTestRoute
  '/api/mcp-test': typeof ApiMcpTestRoute
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/multimodal-tool-result-wire': typeof ApiMultimodalToolResultWireRoute
  '/api/openai-shell-skills-wire': typeof ApiOpenaiShellSkillsWireRoute
  '/api/openai-usage-details': typeof ApiOpenaiUsageDetailsRoute
  '/api/openrouter-cost': typeof ApiOpenrouterCostRoute
  '/api/openrouter-web-tools-wire': typeof ApiOpenrouterWebToolsWireRoute
  '/api/otel-usage': typeof ApiOtelUsageRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tool-call-lifecycle-wire': typeof ApiToolCallLifecycleWireRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider/': typeof ProviderIndexRoute
  '/api/audio/stream': typeof ApiAudioStreamRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-client-default-bridge'
    | '/devtools-chat'
    | '/devtools-generation-hooks'
    | '/devtools-route-a'
    | '/devtools-route-b'
    | '/devtools-structured'
    | '/devtools-tools'
    | '/markdown-cjk'
    | '/middleware-test'
    | '/tools-test'
    | '/$provider/$feature'
    | '/api/anthropic-bug-test'
    | '/api/anthropic-skills-wire'
    | '/api/arktype-tool-wire'
    | '/api/audio'
    | '/api/chat'
    | '/api/image'
    | '/api/mcp-lifecycle-test'
    | '/api/mcp-managed-test'
    | '/api/mcp-server'
    | '/api/mcp-status-test'
    | '/api/mcp-test'
    | '/api/middleware-test'
    | '/api/multimodal-tool-result-wire'
    | '/api/openai-shell-skills-wire'
    | '/api/openai-usage-details'
    | '/api/openrouter-cost'
    | '/api/openrouter-web-tools-wire'
    | '/api/otel-usage'
    | '/api/summarize'
    | '/api/tool-call-lifecycle-wire'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider/'
    | '/api/audio/stream'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-client-default-bridge'
    | '/devtools-chat'
    | '/devtools-generation-hooks'
    | '/devtools-route-a'
    | '/devtools-route-b'
    | '/devtools-structured'
    | '/devtools-tools'
    | '/markdown-cjk'
    | '/middleware-test'
    | '/tools-test'
    | '/$provider/$feature'
    | '/api/anthropic-bug-test'
    | '/api/anthropic-skills-wire'
    | '/api/arktype-tool-wire'
    | '/api/audio'
    | '/api/chat'
    | '/api/image'
    | '/api/mcp-lifecycle-test'
    | '/api/mcp-managed-test'
    | '/api/mcp-server'
    | '/api/mcp-status-test'
    | '/api/mcp-test'
    | '/api/middleware-test'
    | '/api/multimodal-tool-result-wire'
    | '/api/openai-shell-skills-wire'
    | '/api/openai-usage-details'
    | '/api/openrouter-cost'
    | '/api/openrouter-web-tools-wire'
    | '/api/otel-usage'
    | '/api/summarize'
    | '/api/tool-call-lifecycle-wire'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider'
    | '/api/audio/stream'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  id:
    | '__root__'
    | '/'
    | '/chat-client-default-bridge'
    | '/devtools-chat'
    | '/devtools-generation-hooks'
    | '/devtools-route-a'
    | '/devtools-route-b'
    | '/devtools-structured'
    | '/devtools-tools'
    | '/markdown-cjk'
    | '/middleware-test'
    | '/tools-test'
    | '/$provider/$feature'
    | '/api/anthropic-bug-test'
    | '/api/anthropic-skills-wire'
    | '/api/arktype-tool-wire'
    | '/api/audio'
    | '/api/chat'
    | '/api/image'
    | '/api/mcp-lifecycle-test'
    | '/api/mcp-managed-test'
    | '/api/mcp-server'
    | '/api/mcp-status-test'
    | '/api/mcp-test'
    | '/api/middleware-test'
    | '/api/multimodal-tool-result-wire'
    | '/api/openai-shell-skills-wire'
    | '/api/openai-usage-details'
    | '/api/openrouter-cost'
    | '/api/openrouter-web-tools-wire'
    | '/api/otel-usage'
    | '/api/summarize'
    | '/api/tool-call-lifecycle-wire'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider/'
    | '/api/audio/stream'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatClientDefaultBridgeRoute: typeof ChatClientDefaultBridgeRoute
  DevtoolsChatRoute: typeof DevtoolsChatRoute
  DevtoolsGenerationHooksRoute: typeof DevtoolsGenerationHooksRoute
  DevtoolsRouteARoute: typeof DevtoolsRouteARoute
  DevtoolsRouteBRoute: typeof DevtoolsRouteBRoute
  DevtoolsStructuredRoute: typeof DevtoolsStructuredRoute
  DevtoolsToolsRoute: typeof DevtoolsToolsRoute
  MarkdownCjkRoute: typeof MarkdownCjkRoute
  MiddlewareTestRoute: typeof MiddlewareTestRoute
  ToolsTestRoute: typeof ToolsTestRoute
  ProviderFeatureRoute: typeof ProviderFeatureRoute
  ApiAnthropicBugTestRoute: typeof ApiAnthropicBugTestRoute
  ApiAnthropicSkillsWireRoute: typeof ApiAnthropicSkillsWireRoute
  ApiArktypeToolWireRoute: typeof ApiArktypeToolWireRoute
  ApiAudioRoute: typeof ApiAudioRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiImageRoute: typeof ApiImageRouteWithChildren
  ApiMcpLifecycleTestRoute: typeof ApiMcpLifecycleTestRoute
  ApiMcpManagedTestRoute: typeof ApiMcpManagedTestRoute
  ApiMcpServerRoute: typeof ApiMcpServerRoute
  ApiMcpStatusTestRoute: typeof ApiMcpStatusTestRoute
  ApiMcpTestRoute: typeof ApiMcpTestRoute
  ApiMiddlewareTestRoute: typeof ApiMiddlewareTestRoute
  ApiMultimodalToolResultWireRoute: typeof ApiMultimodalToolResultWireRoute
  ApiOpenaiShellSkillsWireRoute: typeof ApiOpenaiShellSkillsWireRoute
  ApiOpenaiUsageDetailsRoute: typeof ApiOpenaiUsageDetailsRoute
  ApiOpenrouterCostRoute: typeof ApiOpenrouterCostRoute
  ApiOpenrouterWebToolsWireRoute: typeof ApiOpenrouterWebToolsWireRoute
  ApiOtelUsageRoute: typeof ApiOtelUsageRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiToolCallLifecycleWireRoute: typeof ApiToolCallLifecycleWireRoute
  ApiToolsTestRoute: typeof ApiToolsTestRoute
  ApiTranscriptionRoute: typeof ApiTranscriptionRouteWithChildren
  ApiTtsRoute: typeof ApiTtsRouteWithChildren
  ApiVideoRoute: typeof ApiVideoRouteWithChildren
  ProviderIndexRoute: typeof ProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools-test': {
      id: '/tools-test'
      path: '/tools-test'
      fullPath: '/tools-test'
      preLoaderRoute: typeof ToolsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware-test': {
      id: '/middleware-test'
      path: '/middleware-test'
      fullPath: '/middleware-test'
      preLoaderRoute: typeof MiddlewareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-cjk': {
      id: '/markdown-cjk'
      path: '/markdown-cjk'
      fullPath: '/markdown-cjk'
      preLoaderRoute: typeof MarkdownCjkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-tools': {
      id: '/devtools-tools'
      path: '/devtools-tools'
      fullPath: '/devtools-tools'
      preLoaderRoute: typeof DevtoolsToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-structured': {
      id: '/devtools-structured'
      path: '/devtools-structured'
      fullPath: '/devtools-structured'
      preLoaderRoute: typeof DevtoolsStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-route-b': {
      id: '/devtools-route-b'
      path: '/devtools-route-b'
      fullPath: '/devtools-route-b'
      preLoaderRoute: typeof DevtoolsRouteBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-route-a': {
      id: '/devtools-route-a'
      path: '/devtools-route-a'
      fullPath: '/devtools-route-a'
      preLoaderRoute: typeof DevtoolsRouteARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-generation-hooks': {
      id: '/devtools-generation-hooks'
      path: '/devtools-generation-hooks'
      fullPath: '/devtools-generation-hooks'
      preLoaderRoute: typeof DevtoolsGenerationHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-chat': {
      id: '/devtools-chat'
      path: '/devtools-chat'
      fullPath: '/devtools-chat'
      preLoaderRoute: typeof DevtoolsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-client-default-bridge': {
      id: '/chat-client-default-bridge'
      path: '/chat-client-default-bridge'
      fullPath: '/chat-client-default-bridge'
      preLoaderRoute: typeof ChatClientDefaultBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$provider/': {
      id: '/$provider/'
      path: '/$provider'
      fullPath: '/$provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcription': {
      id: '/api/transcription'
      path: '/api/transcription'
      fullPath: '/api/transcription'
      preLoaderRoute: typeof ApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools-test': {
      id: '/api/tools-test'
      path: '/api/tools-test'
      fullPath: '/api/tools-test'
      preLoaderRoute: typeof ApiToolsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tool-call-lifecycle-wire': {
      id: '/api/tool-call-lifecycle-wire'
      path: '/api/tool-call-lifecycle-wire'
      fullPath: '/api/tool-call-lifecycle-wire'
      preLoaderRoute: typeof ApiToolCallLifecycleWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otel-usage': {
      id: '/api/otel-usage'
      path: '/api/otel-usage'
      fullPath: '/api/otel-usage'
      preLoaderRoute: typeof ApiOtelUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-web-tools-wire': {
      id: '/api/openrouter-web-tools-wire'
      path: '/api/openrouter-web-tools-wire'
      fullPath: '/api/openrouter-web-tools-wire'
      preLoaderRoute: typeof ApiOpenrouterWebToolsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-cost': {
      id: '/api/openrouter-cost'
      path: '/api/openrouter-cost'
      fullPath: '/api/openrouter-cost'
      preLoaderRoute: typeof ApiOpenrouterCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai-usage-details': {
      id: '/api/openai-usage-details'
      path: '/api/openai-usage-details'
      fullPath: '/api/openai-usage-details'
      preLoaderRoute: typeof ApiOpenaiUsageDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai-shell-skills-wire': {
      id: '/api/openai-shell-skills-wire'
      path: '/api/openai-shell-skills-wire'
      fullPath: '/api/openai-shell-skills-wire'
      preLoaderRoute: typeof ApiOpenaiShellSkillsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multimodal-tool-result-wire': {
      id: '/api/multimodal-tool-result-wire'
      path: '/api/multimodal-tool-result-wire'
      fullPath: '/api/multimodal-tool-result-wire'
      preLoaderRoute: typeof ApiMultimodalToolResultWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/middleware-test': {
      id: '/api/middleware-test'
      path: '/api/middleware-test'
      fullPath: '/api/middleware-test'
      preLoaderRoute: typeof ApiMiddlewareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-test': {
      id: '/api/mcp-test'
      path: '/api/mcp-test'
      fullPath: '/api/mcp-test'
      preLoaderRoute: typeof ApiMcpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-status-test': {
      id: '/api/mcp-status-test'
      path: '/api/mcp-status-test'
      fullPath: '/api/mcp-status-test'
      preLoaderRoute: typeof ApiMcpStatusTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-server': {
      id: '/api/mcp-server'
      path: '/api/mcp-server'
      fullPath: '/api/mcp-server'
      preLoaderRoute: typeof ApiMcpServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-managed-test': {
      id: '/api/mcp-managed-test'
      path: '/api/mcp-managed-test'
      fullPath: '/api/mcp-managed-test'
      preLoaderRoute: typeof ApiMcpManagedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-lifecycle-test': {
      id: '/api/mcp-lifecycle-test'
      path: '/api/mcp-lifecycle-test'
      fullPath: '/api/mcp-lifecycle-test'
      preLoaderRoute: typeof ApiMcpLifecycleTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arktype-tool-wire': {
      id: '/api/arktype-tool-wire'
      path: '/api/arktype-tool-wire'
      fullPath: '/api/arktype-tool-wire'
      preLoaderRoute: typeof ApiArktypeToolWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic-skills-wire': {
      id: '/api/anthropic-skills-wire'
      path: '/api/anthropic-skills-wire'
      fullPath: '/api/anthropic-skills-wire'
      preLoaderRoute: typeof ApiAnthropicSkillsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic-bug-test': {
      id: '/api/anthropic-bug-test'
      path: '/api/anthropic-bug-test'
      fullPath: '/api/anthropic-bug-test'
      preLoaderRoute: typeof ApiAnthropicBugTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$provider/$feature': {
      id: '/$provider/$feature'
      path: '/$provider/$feature'
      fullPath: '/$provider/$feature'
      preLoaderRoute: typeof ProviderFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/stream': {
      id: '/api/video/stream'
      path: '/stream'
      fullPath: '/api/video/stream'
      preLoaderRoute: typeof ApiVideoStreamRouteImport
      parentRoute: typeof ApiVideoRoute
    }
    '/api/tts/stream': {
      id: '/api/tts/stream'
      path: '/stream'
      fullPath: '/api/tts/stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof ApiTtsRoute
    }
    '/api/transcription/stream': {
      id: '/api/transcription/stream'
      path: '/stream'
      fullPath: '/api/transcription/stream'
      preLoaderRoute: typeof ApiTranscriptionStreamRouteImport
      parentRoute: typeof ApiTranscriptionRoute
    }
    '/api/image/stream': {
      id: '/api/image/stream'
      path: '/stream'
      fullPath: '/api/image/stream'
      preLoaderRoute: typeof ApiImageStreamRouteImport
      parentRoute: typeof ApiImageRoute
    }
    '/api/audio/stream': {
      id: '/api/audio/stream'
      path: '/stream'
      fullPath: '/api/audio/stream'
      preLoaderRoute: typeof ApiAudioStreamRouteImport
      parentRoute: typeof ApiAudioRoute
    }
  }
}

interface ApiAudioRouteChildren {
  ApiAudioStreamRoute: typeof ApiAudioStreamRoute
}

const ApiAudioRouteChildren: ApiAudioRouteChildren = {
  ApiAudioStreamRoute: ApiAudioStreamRoute,
}

const ApiAudioRouteWithChildren = ApiAudioRoute._addFileChildren(
  ApiAudioRouteChildren,
)

interface ApiImageRouteChildren {
  ApiImageStreamRoute: typeof ApiImageStreamRoute
}

const ApiImageRouteChildren: ApiImageRouteChildren = {
  ApiImageStreamRoute: ApiImageStreamRoute,
}

const ApiImageRouteWithChildren = ApiImageRoute._addFileChildren(
  ApiImageRouteChildren,
)

interface ApiTranscriptionRouteChildren {
  ApiTranscriptionStreamRoute: typeof ApiTranscriptionStreamRoute
}

const ApiTranscriptionRouteChildren: ApiTranscriptionRouteChildren = {
  ApiTranscriptionStreamRoute: ApiTranscriptionStreamRoute,
}

const ApiTranscriptionRouteWithChildren =
  ApiTranscriptionRoute._addFileChildren(ApiTranscriptionRouteChildren)

interface ApiTtsRouteChildren {
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
}

const ApiTtsRouteChildren: ApiTtsRouteChildren = {
  ApiTtsStreamRoute: ApiTtsStreamRoute,
}

const ApiTtsRouteWithChildren =
  ApiTtsRoute._addFileChildren(ApiTtsRouteChildren)

interface ApiVideoRouteChildren {
  ApiVideoStreamRoute: typeof ApiVideoStreamRoute
}

const ApiVideoRouteChildren: ApiVideoRouteChildren = {
  ApiVideoStreamRoute: ApiVideoStreamRoute,
}

const ApiVideoRouteWithChildren = ApiVideoRoute._addFileChildren(
  ApiVideoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatClientDefaultBridgeRoute: ChatClientDefaultBridgeRoute,
  DevtoolsChatRoute: DevtoolsChatRoute,
  DevtoolsGenerationHooksRoute: DevtoolsGenerationHooksRoute,
  DevtoolsRouteARoute: DevtoolsRouteARoute,
  DevtoolsRouteBRoute: DevtoolsRouteBRoute,
  DevtoolsStructuredRoute: DevtoolsStructuredRoute,
  DevtoolsToolsRoute: DevtoolsToolsRoute,
  MarkdownCjkRoute: MarkdownCjkRoute,
  MiddlewareTestRoute: MiddlewareTestRoute,
  ToolsTestRoute: ToolsTestRoute,
  ProviderFeatureRoute: ProviderFeatureRoute,
  ApiAnthropicBugTestRoute: ApiAnthropicBugTestRoute,
  ApiAnthropicSkillsWireRoute: ApiAnthropicSkillsWireRoute,
  ApiArktypeToolWireRoute: ApiArktypeToolWireRoute,
  ApiAudioRoute: ApiAudioRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiImageRoute: ApiImageRouteWithChildren,
  ApiMcpLifecycleTestRoute: ApiMcpLifecycleTestRoute,
  ApiMcpManagedTestRoute: ApiMcpManagedTestRoute,
  ApiMcpServerRoute: ApiMcpServerRoute,
  ApiMcpStatusTestRoute: ApiMcpStatusTestRoute,
  ApiMcpTestRoute: ApiMcpTestRoute,
  ApiMiddlewareTestRoute: ApiMiddlewareTestRoute,
  ApiMultimodalToolResultWireRoute: ApiMultimodalToolResultWireRoute,
  ApiOpenaiShellSkillsWireRoute: ApiOpenaiShellSkillsWireRoute,
  ApiOpenaiUsageDetailsRoute: ApiOpenaiUsageDetailsRoute,
  ApiOpenrouterCostRoute: ApiOpenrouterCostRoute,
  ApiOpenrouterWebToolsWireRoute: ApiOpenrouterWebToolsWireRoute,
  ApiOtelUsageRoute: ApiOtelUsageRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiToolCallLifecycleWireRoute: ApiToolCallLifecycleWireRoute,
  ApiToolsTestRoute: ApiToolsTestRoute,
  ApiTranscriptionRoute: ApiTranscriptionRouteWithChildren,
  ApiTtsRoute: ApiTtsRouteWithChildren,
  ApiVideoRoute: ApiVideoRouteWithChildren,
  ProviderIndexRoute: ProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
