/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as ServerFnChatRouteImport } from './routes/server-fn-chat'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as McpDemoRouteImport } from './routes/mcp-demo'
import { Route as Issue176ToolResultRouteImport } from './routes/issue-176-tool-result'
import { Route as ImageToolReproRouteImport } from './routes/image-tool-repro'
import { Route as ImageGenRouteImport } from './routes/image-gen'
import { Route as GenerationHooksRouteImport } from './routes/generation-hooks'
import { Route as CapabilityDemoRouteImport } from './routes/capability-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerationsVideoRouteImport } from './routes/generations.video'
import { Route as GenerationsTranscriptionRouteImport } from './routes/generations.transcription'
import { Route as GenerationsSummarizeRouteImport } from './routes/generations.summarize'
import { Route as GenerationsStructuredOutputRouteImport } from './routes/generations.structured-output'
import { Route as GenerationsStructuredChatRouteImport } from './routes/generations.structured-chat'
import { Route as GenerationsSpeechRouteImport } from './routes/generations.speech'
import { Route as GenerationsImageRouteImport } from './routes/generations.image'
import { Route as GenerationsAudioRouteImport } from './routes/generations.audio'
import { Route as ExampleRuntimeContextRouteImport } from './routes/example.runtime-context'
import { Route as ApiTranscribeRouteImport } from './routes/api.transcribe'
import { Route as ApiTanchatRouteImport } from './routes/api.tanchat'
import { Route as ApiSummarizeRouteImport } from './routes/api.summarize'
import { Route as ApiStructuredOutputRouteImport } from './routes/api.structured-output'
import { Route as ApiStructuredChatRouteImport } from './routes/api.structured-chat'
import { Route as ApiMcpStatusRouteImport } from './routes/api.mcp-status'
import { Route as ApiMcpPoolRouteImport } from './routes/api.mcp-pool'
import { Route as ApiMcpManualRouteImport } from './routes/api.mcp-manual'
import { Route as ApiMcpChatRouteImport } from './routes/api.mcp-chat'
import { Route as ApiImageToolReproRouteImport } from './routes/api.image-tool-repro'
import { Route as ApiImageGenRouteImport } from './routes/api.image-gen'
import { Route as ApiCapabilityDemoRouteImport } from './routes/api.capability-demo'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'
import { Route as ApiGenerateVideoRouteImport } from './routes/api.generate.video'
import { Route as ApiGenerateSpeechRouteImport } from './routes/api.generate.speech'
import { Route as ApiGenerateImageRouteImport } from './routes/api.generate.image'
import { Route as ApiGenerateAudioRouteImport } from './routes/api.generate.audio'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerFnChatRoute = ServerFnChatRouteImport.update({
  id: '/server-fn-chat',
  path: '/server-fn-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const McpDemoRoute = McpDemoRouteImport.update({
  id: '/mcp-demo',
  path: '/mcp-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const Issue176ToolResultRoute = Issue176ToolResultRouteImport.update({
  id: '/issue-176-tool-result',
  path: '/issue-176-tool-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolReproRoute = ImageToolReproRouteImport.update({
  id: '/image-tool-repro',
  path: '/image-tool-repro',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGenRoute = ImageGenRouteImport.update({
  id: '/image-gen',
  path: '/image-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationHooksRoute = GenerationHooksRouteImport.update({
  id: '/generation-hooks',
  path: '/generation-hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityDemoRoute = CapabilityDemoRouteImport.update({
  id: '/capability-demo',
  path: '/capability-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsVideoRoute = GenerationsVideoRouteImport.update({
  id: '/generations/video',
  path: '/generations/video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsTranscriptionRoute =
  GenerationsTranscriptionRouteImport.update({
    id: '/generations/transcription',
    path: '/generations/transcription',
    getParentRoute: () => rootRouteImport,
  } as any)
const GenerationsSummarizeRoute = GenerationsSummarizeRouteImport.update({
  id: '/generations/summarize',
  path: '/generations/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsStructuredOutputRoute =
  GenerationsStructuredOutputRouteImport.update({
    id: '/generations/structured-output',
    path: '/generations/structured-output',
    getParentRoute: () => rootRouteImport,
  } as any)
const GenerationsStructuredChatRoute =
  GenerationsStructuredChatRouteImport.update({
    id: '/generations/structured-chat',
    path: '/generations/structured-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const GenerationsSpeechRoute = GenerationsSpeechRouteImport.update({
  id: '/generations/speech',
  path: '/generations/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsImageRoute = GenerationsImageRouteImport.update({
  id: '/generations/image',
  path: '/generations/image',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsAudioRoute = GenerationsAudioRouteImport.update({
  id: '/generations/audio',
  path: '/generations/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRuntimeContextRoute = ExampleRuntimeContextRouteImport.update({
  id: '/example/runtime-context',
  path: '/example/runtime-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTanchatRoute = ApiTanchatRouteImport.update({
  id: '/api/tanchat',
  path: '/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStructuredOutputRoute = ApiStructuredOutputRouteImport.update({
  id: '/api/structured-output',
  path: '/api/structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStructuredChatRoute = ApiStructuredChatRouteImport.update({
  id: '/api/structured-chat',
  path: '/api/structured-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpStatusRoute = ApiMcpStatusRouteImport.update({
  id: '/api/mcp-status',
  path: '/api/mcp-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpPoolRoute = ApiMcpPoolRouteImport.update({
  id: '/api/mcp-pool',
  path: '/api/mcp-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpManualRoute = ApiMcpManualRouteImport.update({
  id: '/api/mcp-manual',
  path: '/api/mcp-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpChatRoute = ApiMcpChatRouteImport.update({
  id: '/api/mcp-chat',
  path: '/api/mcp-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageToolReproRoute = ApiImageToolReproRouteImport.update({
  id: '/api/image-tool-repro',
  path: '/api/image-tool-repro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageGenRoute = ApiImageGenRouteImport.update({
  id: '/api/image-gen',
  path: '/api/image-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapabilityDemoRoute = ApiCapabilityDemoRouteImport.update({
  id: '/api/capability-demo',
  path: '/api/capability-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate/video',
  path: '/api/generate/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSpeechRoute = ApiGenerateSpeechRouteImport.update({
  id: '/api/generate/speech',
  path: '/api/generate/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate/image',
  path: '/api/generate/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAudioRoute = ApiGenerateAudioRouteImport.update({
  id: '/api/generate/audio',
  path: '/api/generate/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capability-demo': typeof CapabilityDemoRoute
  '/generation-hooks': typeof GenerationHooksRoute
  '/image-gen': typeof ImageGenRoute
  '/image-tool-repro': typeof ImageToolReproRoute
  '/issue-176-tool-result': typeof Issue176ToolResultRoute
  '/mcp-demo': typeof McpDemoRoute
  '/realtime': typeof RealtimeRoute
  '/server-fn-chat': typeof ServerFnChatRoute
  '/threads': typeof ThreadsRoute
  '/api/capability-demo': typeof ApiCapabilityDemoRoute
  '/api/image-gen': typeof ApiImageGenRoute
  '/api/image-tool-repro': typeof ApiImageToolReproRoute
  '/api/mcp-chat': typeof ApiMcpChatRoute
  '/api/mcp-manual': typeof ApiMcpManualRoute
  '/api/mcp-pool': typeof ApiMcpPoolRoute
  '/api/mcp-status': typeof ApiMcpStatusRoute
  '/api/structured-chat': typeof ApiStructuredChatRoute
  '/api/structured-output': typeof ApiStructuredOutputRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/example/runtime-context': typeof ExampleRuntimeContextRoute
  '/generations/audio': typeof GenerationsAudioRoute
  '/generations/image': typeof GenerationsImageRoute
  '/generations/speech': typeof GenerationsSpeechRoute
  '/generations/structured-chat': typeof GenerationsStructuredChatRoute
  '/generations/structured-output': typeof GenerationsStructuredOutputRoute
  '/generations/summarize': typeof GenerationsSummarizeRoute
  '/generations/transcription': typeof GenerationsTranscriptionRoute
  '/generations/video': typeof GenerationsVideoRoute
  '/api/generate/audio': typeof ApiGenerateAudioRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/speech': typeof ApiGenerateSpeechRoute
  '/api/generate/video': typeof ApiGenerateVideoRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capability-demo': typeof CapabilityDemoRoute
  '/generation-hooks': typeof GenerationHooksRoute
  '/image-gen': typeof ImageGenRoute
  '/image-tool-repro': typeof ImageToolReproRoute
  '/issue-176-tool-result': typeof Issue176ToolResultRoute
  '/mcp-demo': typeof McpDemoRoute
  '/realtime': typeof RealtimeRoute
  '/server-fn-chat': typeof ServerFnChatRoute
  '/threads': typeof ThreadsRoute
  '/api/capability-demo': typeof ApiCapabilityDemoRoute
  '/api/image-gen': typeof ApiImageGenRoute
  '/api/image-tool-repro': typeof ApiImageToolReproRoute
  '/api/mcp-chat': typeof ApiMcpChatRoute
  '/api/mcp-manual': typeof ApiMcpManualRoute
  '/api/mcp-pool': typeof ApiMcpPoolRoute
  '/api/mcp-status': typeof ApiMcpStatusRoute
  '/api/structured-chat': typeof ApiStructuredChatRoute
  '/api/structured-output': typeof ApiStructuredOutputRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/example/runtime-context': typeof ExampleRuntimeContextRoute
  '/generations/audio': typeof GenerationsAudioRoute
  '/generations/image': typeof GenerationsImageRoute
  '/generations/speech': typeof GenerationsSpeechRoute
  '/generations/structured-chat': typeof GenerationsStructuredChatRoute
  '/generations/structured-output': typeof GenerationsStructuredOutputRoute
  '/generations/summarize': typeof GenerationsSummarizeRoute
  '/generations/transcription': typeof GenerationsTranscriptionRoute
  '/generations/video': typeof GenerationsVideoRoute
  '/api/generate/audio': typeof ApiGenerateAudioRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/speech': typeof ApiGenerateSpeechRoute
  '/api/generate/video': typeof ApiGenerateVideoRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capability-demo': typeof CapabilityDemoRoute
  '/generation-hooks': typeof GenerationHooksRoute
  '/image-gen': typeof ImageGenRoute
  '/image-tool-repro': typeof ImageToolReproRoute
  '/issue-176-tool-result': typeof Issue176ToolResultRoute
  '/mcp-demo': typeof McpDemoRoute
  '/realtime': typeof RealtimeRoute
  '/server-fn-chat': typeof ServerFnChatRoute
  '/threads': typeof ThreadsRoute
  '/api/capability-demo': typeof ApiCapabilityDemoRoute
  '/api/image-gen': typeof ApiImageGenRoute
  '/api/image-tool-repro': typeof ApiImageToolReproRoute
  '/api/mcp-chat': typeof ApiMcpChatRoute
  '/api/mcp-manual': typeof ApiMcpManualRoute
  '/api/mcp-pool': typeof ApiMcpPoolRoute
  '/api/mcp-status': typeof ApiMcpStatusRoute
  '/api/structured-chat': typeof ApiStructuredChatRoute
  '/api/structured-output': typeof ApiStructuredOutputRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tanchat': typeof ApiTanchatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/example/runtime-context': typeof ExampleRuntimeContextRoute
  '/generations/audio': typeof GenerationsAudioRoute
  '/generations/image': typeof GenerationsImageRoute
  '/generations/speech': typeof GenerationsSpeechRoute
  '/generations/structured-chat': typeof GenerationsStructuredChatRoute
  '/generations/structured-output': typeof GenerationsStructuredOutputRoute
  '/generations/summarize': typeof GenerationsSummarizeRoute
  '/generations/transcription': typeof GenerationsTranscriptionRoute
  '/generations/video': typeof GenerationsVideoRoute
  '/api/generate/audio': typeof ApiGenerateAudioRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/speech': typeof ApiGenerateSpeechRoute
  '/api/generate/video': typeof ApiGenerateVideoRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capability-demo'
    | '/generation-hooks'
    | '/image-gen'
    | '/image-tool-repro'
    | '/issue-176-tool-result'
    | '/mcp-demo'
    | '/realtime'
    | '/server-fn-chat'
    | '/threads'
    | '/api/capability-demo'
    | '/api/image-gen'
    | '/api/image-tool-repro'
    | '/api/mcp-chat'
    | '/api/mcp-manual'
    | '/api/mcp-pool'
    | '/api/mcp-status'
    | '/api/structured-chat'
    | '/api/structured-output'
    | '/api/summarize'
    | '/api/tanchat'
    | '/api/transcribe'
    | '/example/runtime-context'
    | '/generations/audio'
    | '/generations/image'
    | '/generations/speech'
    | '/generations/structured-chat'
    | '/generations/structured-output'
    | '/generations/summarize'
    | '/generations/transcription'
    | '/generations/video'
    | '/api/generate/audio'
    | '/api/generate/image'
    | '/api/generate/speech'
    | '/api/generate/video'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capability-demo'
    | '/generation-hooks'
    | '/image-gen'
    | '/image-tool-repro'
    | '/issue-176-tool-result'
    | '/mcp-demo'
    | '/realtime'
    | '/server-fn-chat'
    | '/threads'
    | '/api/capability-demo'
    | '/api/image-gen'
    | '/api/image-tool-repro'
    | '/api/mcp-chat'
    | '/api/mcp-manual'
    | '/api/mcp-pool'
    | '/api/mcp-status'
    | '/api/structured-chat'
    | '/api/structured-output'
    | '/api/summarize'
    | '/api/tanchat'
    | '/api/transcribe'
    | '/example/runtime-context'
    | '/generations/audio'
    | '/generations/image'
    | '/generations/speech'
    | '/generations/structured-chat'
    | '/generations/structured-output'
    | '/generations/summarize'
    | '/generations/transcription'
    | '/generations/video'
    | '/api/generate/audio'
    | '/api/generate/image'
    | '/api/generate/speech'
    | '/api/generate/video'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
  id:
    | '__root__'
    | '/'
    | '/capability-demo'
    | '/generation-hooks'
    | '/image-gen'
    | '/image-tool-repro'
    | '/issue-176-tool-result'
    | '/mcp-demo'
    | '/realtime'
    | '/server-fn-chat'
    | '/threads'
    | '/api/capability-demo'
    | '/api/image-gen'
    | '/api/image-tool-repro'
    | '/api/mcp-chat'
    | '/api/mcp-manual'
    | '/api/mcp-pool'
    | '/api/mcp-status'
    | '/api/structured-chat'
    | '/api/structured-output'
    | '/api/summarize'
    | '/api/tanchat'
    | '/api/transcribe'
    | '/example/runtime-context'
    | '/generations/audio'
    | '/generations/image'
    | '/generations/speech'
    | '/generations/structured-chat'
    | '/generations/structured-output'
    | '/generations/summarize'
    | '/generations/transcription'
    | '/generations/video'
    | '/api/generate/audio'
    | '/api/generate/image'
    | '/api/generate/speech'
    | '/api/generate/video'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilityDemoRoute: typeof CapabilityDemoRoute
  GenerationHooksRoute: typeof GenerationHooksRoute
  ImageGenRoute: typeof ImageGenRoute
  ImageToolReproRoute: typeof ImageToolReproRoute
  Issue176ToolResultRoute: typeof Issue176ToolResultRoute
  McpDemoRoute: typeof McpDemoRoute
  RealtimeRoute: typeof RealtimeRoute
  ServerFnChatRoute: typeof ServerFnChatRoute
  ThreadsRoute: typeof ThreadsRoute
  ApiCapabilityDemoRoute: typeof ApiCapabilityDemoRoute
  ApiImageGenRoute: typeof ApiImageGenRoute
  ApiImageToolReproRoute: typeof ApiImageToolReproRoute
  ApiMcpChatRoute: typeof ApiMcpChatRoute
  ApiMcpManualRoute: typeof ApiMcpManualRoute
  ApiMcpPoolRoute: typeof ApiMcpPoolRoute
  ApiMcpStatusRoute: typeof ApiMcpStatusRoute
  ApiStructuredChatRoute: typeof ApiStructuredChatRoute
  ApiStructuredOutputRoute: typeof ApiStructuredOutputRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiTanchatRoute: typeof ApiTanchatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ExampleRuntimeContextRoute: typeof ExampleRuntimeContextRoute
  GenerationsAudioRoute: typeof GenerationsAudioRoute
  GenerationsImageRoute: typeof GenerationsImageRoute
  GenerationsSpeechRoute: typeof GenerationsSpeechRoute
  GenerationsStructuredChatRoute: typeof GenerationsStructuredChatRoute
  GenerationsStructuredOutputRoute: typeof GenerationsStructuredOutputRoute
  GenerationsSummarizeRoute: typeof GenerationsSummarizeRoute
  GenerationsTranscriptionRoute: typeof GenerationsTranscriptionRoute
  GenerationsVideoRoute: typeof GenerationsVideoRoute
  ApiGenerateAudioRoute: typeof ApiGenerateAudioRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateSpeechRoute: typeof ApiGenerateSpeechRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-fn-chat': {
      id: '/server-fn-chat'
      path: '/server-fn-chat'
      fullPath: '/server-fn-chat'
      preLoaderRoute: typeof ServerFnChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-demo': {
      id: '/mcp-demo'
      path: '/mcp-demo'
      fullPath: '/mcp-demo'
      preLoaderRoute: typeof McpDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue-176-tool-result': {
      id: '/issue-176-tool-result'
      path: '/issue-176-tool-result'
      fullPath: '/issue-176-tool-result'
      preLoaderRoute: typeof Issue176ToolResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tool-repro': {
      id: '/image-tool-repro'
      path: '/image-tool-repro'
      fullPath: '/image-tool-repro'
      preLoaderRoute: typeof ImageToolReproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-gen': {
      id: '/image-gen'
      path: '/image-gen'
      fullPath: '/image-gen'
      preLoaderRoute: typeof ImageGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-hooks': {
      id: '/generation-hooks'
      path: '/generation-hooks'
      fullPath: '/generation-hooks'
      preLoaderRoute: typeof GenerationHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-demo': {
      id: '/capability-demo'
      path: '/capability-demo'
      fullPath: '/capability-demo'
      preLoaderRoute: typeof CapabilityDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/video': {
      id: '/generations/video'
      path: '/generations/video'
      fullPath: '/generations/video'
      preLoaderRoute: typeof GenerationsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/transcription': {
      id: '/generations/transcription'
      path: '/generations/transcription'
      fullPath: '/generations/transcription'
      preLoaderRoute: typeof GenerationsTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/summarize': {
      id: '/generations/summarize'
      path: '/generations/summarize'
      fullPath: '/generations/summarize'
      preLoaderRoute: typeof GenerationsSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/structured-output': {
      id: '/generations/structured-output'
      path: '/generations/structured-output'
      fullPath: '/generations/structured-output'
      preLoaderRoute: typeof GenerationsStructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/structured-chat': {
      id: '/generations/structured-chat'
      path: '/generations/structured-chat'
      fullPath: '/generations/structured-chat'
      preLoaderRoute: typeof GenerationsStructuredChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/speech': {
      id: '/generations/speech'
      path: '/generations/speech'
      fullPath: '/generations/speech'
      preLoaderRoute: typeof GenerationsSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/image': {
      id: '/generations/image'
      path: '/generations/image'
      fullPath: '/generations/image'
      preLoaderRoute: typeof GenerationsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/audio': {
      id: '/generations/audio'
      path: '/generations/audio'
      fullPath: '/generations/audio'
      preLoaderRoute: typeof GenerationsAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/runtime-context': {
      id: '/example/runtime-context'
      path: '/example/runtime-context'
      fullPath: '/example/runtime-context'
      preLoaderRoute: typeof ExampleRuntimeContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tanchat': {
      id: '/api/tanchat'
      path: '/api/tanchat'
      fullPath: '/api/tanchat'
      preLoaderRoute: typeof ApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/structured-output': {
      id: '/api/structured-output'
      path: '/api/structured-output'
      fullPath: '/api/structured-output'
      preLoaderRoute: typeof ApiStructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/structured-chat': {
      id: '/api/structured-chat'
      path: '/api/structured-chat'
      fullPath: '/api/structured-chat'
      preLoaderRoute: typeof ApiStructuredChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-status': {
      id: '/api/mcp-status'
      path: '/api/mcp-status'
      fullPath: '/api/mcp-status'
      preLoaderRoute: typeof ApiMcpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-pool': {
      id: '/api/mcp-pool'
      path: '/api/mcp-pool'
      fullPath: '/api/mcp-pool'
      preLoaderRoute: typeof ApiMcpPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-manual': {
      id: '/api/mcp-manual'
      path: '/api/mcp-manual'
      fullPath: '/api/mcp-manual'
      preLoaderRoute: typeof ApiMcpManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-chat': {
      id: '/api/mcp-chat'
      path: '/api/mcp-chat'
      fullPath: '/api/mcp-chat'
      preLoaderRoute: typeof ApiMcpChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-tool-repro': {
      id: '/api/image-tool-repro'
      path: '/api/image-tool-repro'
      fullPath: '/api/image-tool-repro'
      preLoaderRoute: typeof ApiImageToolReproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-gen': {
      id: '/api/image-gen'
      path: '/api/image-gen'
      fullPath: '/api/image-gen'
      preLoaderRoute: typeof ApiImageGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capability-demo': {
      id: '/api/capability-demo'
      path: '/api/capability-demo'
      fullPath: '/api/capability-demo'
      preLoaderRoute: typeof ApiCapabilityDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars/'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/video': {
      id: '/api/generate/video'
      path: '/api/generate/video'
      fullPath: '/api/generate/video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/speech': {
      id: '/api/generate/speech'
      path: '/api/generate/speech'
      fullPath: '/api/generate/speech'
      preLoaderRoute: typeof ApiGenerateSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/image': {
      id: '/api/generate/image'
      path: '/api/generate/image'
      fullPath: '/api/generate/image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/audio': {
      id: '/api/generate/audio'
      path: '/api/generate/audio'
      fullPath: '/api/generate/audio'
      preLoaderRoute: typeof ApiGenerateAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilityDemoRoute: CapabilityDemoRoute,
  GenerationHooksRoute: GenerationHooksRoute,
  ImageGenRoute: ImageGenRoute,
  ImageToolReproRoute: ImageToolReproRoute,
  Issue176ToolResultRoute: Issue176ToolResultRoute,
  McpDemoRoute: McpDemoRoute,
  RealtimeRoute: RealtimeRoute,
  ServerFnChatRoute: ServerFnChatRoute,
  ThreadsRoute: ThreadsRoute,
  ApiCapabilityDemoRoute: ApiCapabilityDemoRoute,
  ApiImageGenRoute: ApiImageGenRoute,
  ApiImageToolReproRoute: ApiImageToolReproRoute,
  ApiMcpChatRoute: ApiMcpChatRoute,
  ApiMcpManualRoute: ApiMcpManualRoute,
  ApiMcpPoolRoute: ApiMcpPoolRoute,
  ApiMcpStatusRoute: ApiMcpStatusRoute,
  ApiStructuredChatRoute: ApiStructuredChatRoute,
  ApiStructuredOutputRoute: ApiStructuredOutputRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiTanchatRoute: ApiTanchatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ExampleRuntimeContextRoute: ExampleRuntimeContextRoute,
  GenerationsAudioRoute: GenerationsAudioRoute,
  GenerationsImageRoute: GenerationsImageRoute,
  GenerationsSpeechRoute: GenerationsSpeechRoute,
  GenerationsStructuredChatRoute: GenerationsStructuredChatRoute,
  GenerationsStructuredOutputRoute: GenerationsStructuredOutputRoute,
  GenerationsSummarizeRoute: GenerationsSummarizeRoute,
  GenerationsTranscriptionRoute: GenerationsTranscriptionRoute,
  GenerationsVideoRoute: GenerationsVideoRoute,
  ApiGenerateAudioRoute: ApiGenerateAudioRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateSpeechRoute: ApiGenerateSpeechRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
