import { describe, it, expect } from 'vitest'
import {
  filterChatModels,
  filterImageModels,
  generateModelUnionSource,
  resolveOpenAIConfig,
} from '../src/providers/openai'
import type { ModelInfo } from '../src/types'

describe('resolveOpenAIConfig', () => {
  it('returns default config', () => {
    const config = resolveOpenAIConfig()
    expect(config.name).toBe('openai')
    expect(config.specUrl).toContain('stainless.com')
    expect(config.modelsEndpoint).toBe('https://api.openai.com/v1/models')
    expect(config.apiKeyEnvVar).toBe('OPENAI_API_KEY')
  })

  it('allows overriding fields', () => {
    const config = resolveOpenAIConfig({
      specUrl: 'http://custom.spec/openapi.yaml',
      apiKey: 'sk-test-key',
    })
    expect(config.specUrl).toBe('http://custom.spec/openapi.yaml')
    expect(config.apiKey).toBe('sk-test-key')
  })
})

describe('filterChatModels', () => {
  const sampleModels: Array<ModelInfo> = [
    { id: 'gpt-4o', owned_by: 'openai' },
    { id: 'gpt-4o-mini', owned_by: 'openai' },
    { id: 'gpt-3.5-turbo', owned_by: 'openai' },
    { id: 'o3', owned_by: 'openai' },
    { id: 'o3-mini', owned_by: 'openai' },
    { id: 'o4-mini', owned_by: 'openai' },
    { id: 'chatgpt-4o-latest', owned_by: 'openai' },
    { id: 'gpt-4o-realtime-preview', owned_by: 'openai' },
    { id: 'gpt-4o-transcribe-2025-01-01', owned_by: 'openai' },
    { id: 'gpt-4o-tts-2025-01-01', owned_by: 'openai' },
    { id: 'gpt-image-1', owned_by: 'openai' },
    { id: 'dall-e-3', owned_by: 'openai' },
    { id: 'text-embedding-3-small', owned_by: 'openai' },
    { id: 'whisper-1', owned_by: 'openai' },
    { id: 'tts-1', owned_by: 'openai' },
    { id: 'codex-mini-latest', owned_by: 'openai' },
  ]

  it('includes chat-capable models', () => {
    const chat = filterChatModels(sampleModels)
    const ids = chat.map((m) => m.id)

    expect(ids).toContain('gpt-4o')
    expect(ids).toContain('gpt-4o-mini')
    expect(ids).toContain('gpt-3.5-turbo')
    expect(ids).toContain('o3')
    expect(ids).toContain('o3-mini')
    expect(ids).toContain('o4-mini')
    expect(ids).toContain('chatgpt-4o-latest')
    expect(ids).toContain('codex-mini-latest')
  })

  it('excludes realtime, transcribe, tts models', () => {
    const chat = filterChatModels(sampleModels)
    const ids = chat.map((m) => m.id)

    expect(ids).not.toContain('gpt-4o-realtime-preview')
    expect(ids).not.toContain('gpt-4o-transcribe-2025-01-01')
    expect(ids).not.toContain('gpt-4o-tts-2025-01-01')
  })

  it('excludes non-chat models', () => {
    const chat = filterChatModels(sampleModels)
    const ids = chat.map((m) => m.id)

    expect(ids).not.toContain('gpt-image-1')
    expect(ids).not.toContain('dall-e-3')
    expect(ids).not.toContain('text-embedding-3-small')
    expect(ids).not.toContain('whisper-1')
    expect(ids).not.toContain('tts-1')
  })
})

describe('filterImageModels', () => {
  const sampleModels: Array<ModelInfo> = [
    { id: 'gpt-4o', owned_by: 'openai' },
    { id: 'gpt-image-1', owned_by: 'openai' },
    { id: 'gpt-image-1-mini', owned_by: 'openai' },
    { id: 'dall-e-3', owned_by: 'openai' },
    { id: 'dall-e-2', owned_by: 'openai' },
  ]

  it('includes only image generation models', () => {
    const images = filterImageModels(sampleModels)
    const ids = images.map((m) => m.id)

    expect(ids).toContain('gpt-image-1')
    expect(ids).toContain('gpt-image-1-mini')
    expect(ids).toContain('dall-e-3')
    expect(ids).toContain('dall-e-2')
    expect(ids).not.toContain('gpt-4o')
  })
})

describe('generateModelUnionSource', () => {
  it('generates valid TypeScript with model unions', () => {
    const chatModels: Array<ModelInfo> = [
      { id: 'gpt-4o' },
      { id: 'gpt-4o-mini' },
      { id: 'o3' },
    ]
    const imageModels: Array<ModelInfo> = [
      { id: 'gpt-image-1' },
      { id: 'dall-e-3' },
    ]

    const source = generateModelUnionSource(chatModels, imageModels)

    // Check it contains the model strings
    expect(source).toContain("'gpt-4o'")
    expect(source).toContain("'gpt-4o-mini'")
    expect(source).toContain("'o3'")
    expect(source).toContain("'gpt-image-1'")
    expect(source).toContain("'dall-e-3'")

    // Check it has the proper exports
    expect(source).toContain('export const OPENAI_CHAT_MODELS')
    expect(source).toContain('export type OpenAIChatModel')
    expect(source).toContain('export const OPENAI_IMAGE_MODELS')
    expect(source).toContain('export type OpenAIImageModel')

    // Check it has the auto-generated header
    expect(source).toContain('Auto-generated by @tanstack/ai-vite')
  })

  it('handles empty model lists gracefully', () => {
    const source = generateModelUnionSource([], [])

    expect(source).toContain('export const OPENAI_CHAT_MODELS = [] as const')
    expect(source).toContain('export type OpenAIChatModel = string')
    // No image models section when empty
    expect(source).not.toContain('OPENAI_IMAGE_MODELS')
  })
})
